version: '3.7'
services:
  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      my-network:
networks:
  my-network:
    external: true
    name: suhan-network
