version: '3.7'
services:
  catalog-service:
    container_name: catalog-service
    image: completed0728/catalog-service:1.0
    environment:
      eureka.client.serviceUrl.defaultZone: http://naming-server:8761/eureka
      spring.datasource.url: jdbc:mysql://mysql:3306/msa?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true
      logging.file: /api-logs/catalog-ws.log
    networks:
      my-network:
networks:
  my-network:
    external: true
    name: suhan-network