version: '3.7'
services:
  prometheus:
    container_name: prometheus
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - D:\prometheus\prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      my-network:
networks:
  my-network:
    external: true
    name: suhan-network