version: '3.7'
services:
  order-service:
    container_name: order-service
    image: completed0728/order-service:1.0
    environment:
      spring.rabbitmq.host: rabbitmq
      spring.config.import: optional:configserver:http://config-server:8888
      management.zipkin.tracing.endpoint: http://zipkin:9411/api/v2/spans
      eureka.client.serviceUrl.defaultZone: http://naming-server:8761/eureka
      spring.datasource.url: jdbc:mysql://mysql:3306/msa?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true
      logging.file: /api-logs/order-ws.log
    networks:
      my-network:
networks:
  my-network:
    external: true
    name: suhan-network
