version: '3.7'
services:
  gateway-service:
    container_name: gateway-service
    image: completed0728/gateway-service:1.0
    ports:
      - "8000:8000"
    environment:
      spring.rabbitmq.host: rabbitmq
      spring.config.import: optional:configserver:http://config-server:8888
      eureka.client.serviceUrl.defaultZone: http://naming-server:8761/eureka
    #    depends_on:
    #      - rabbitmq
    #      - config-server
    #      - naming-server
    networks:
      my-network:
networks:
  my-network:
    external: true
    name: suhan-network
